version: '3.8'

services:
  backend:
    image: dinosaursmallli/red-ai-backend:v1
    container_name: red-ai-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: dinosaursmallli/red-ai-frontend:v1
    container_name: red-ai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
